namespace: development
mysql:
  auth:
    username: devuser
    password: devpassword
    database: devdatabase
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 1Gi
service:
  type: ClusterIP
  port: 8080
image:
  tag: dev
